//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public int ID_Veiculo { get; set; }
        public int ID_Pessoa { get; set; }
        public string Placa { get; set; }
        public string Montadora { get; set; }
        public string Modelo { get; set; }
        public string Ano { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
