//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudoProva1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        public int Id_Carro { get; set; }
        public string Montadora { get; set; }
        public string Modelo { get; set; }
        public string Ano { get; set; }
        public string Cor { get; set; }
        public string Placa { get; set; }
        public Nullable<int> Id_Proprietario { get; set; }
    
        public virtual Proprietario Proprietario { get; set; }
    }
}
