//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA
    {
        public int IdNota { get; set; }
        public int IdAcademico { get; set; }
        public string NomeMateria { get; set; }
        public decimal NotaI { get; set; }
        public decimal NotaII { get; set; }
        public decimal NotaIII { get; set; }
        public decimal NotaIIII { get; set; }
    
        public virtual Academico Academico { get; set; }
    }
}
